"""EWFD scattered-field study + result extraction.

Physics setup (per issue #10):
* Electromagnetic Waves, Frequency Domain (EWFD).
* Scattered-field formulation: solve for the scattered field on top of an
  x-polarised plane wave traveling in +z: E_bg = exp(-i·k·z) x̂.
* Scattering (matched) boundary conditions on the inlet (z=0) and outlet
  (z=L) end-caps of the external cylinder.
* MUMPS direct solver, frequency-domain study.

Result extraction:
* Axial profile: |E|(z) sampled along the z-axis (x=0, y=0).
* Axial slice: |E|(x, z) sampled at y=0 over a rectangular grid spanning
  the geometry.
"""

from __future__ import annotations

from typing import Any

import numpy as np

from thznerve.model.geometry import GeometryParams, total_length_um


# --- Physics setup ---------------------------------------------------------


def _add_box_selection(
    geom_java: Any,
    tag: str,
    label: str,
    *,
    entity_dim: int,
    xmin: float, xmax: float,
    ymin: float, ymax: float,
    zmin: float, zmax: float,
) -> None:
    sel = geom_java.feature().create(tag, "BoxSelection")
    sel.set("entitydim", str(entity_dim))
    sel.set("xmin", str(xmin)); sel.set("xmax", str(xmax))
    sel.set("ymin", str(ymin)); sel.set("ymax", str(ymax))
    sel.set("zmin", str(zmin)); sel.set("zmax", str(zmax))
    sel.set("condition", "inside")
    sel.label(label)


def add_endcap_selections(model: Any, geom_params: GeometryParams) -> tuple[str, str]:
    """Add box selections that pick the inlet (z=0) and outlet (z=L) end-cap faces.

    Returns (inlet_selection_tag, outlet_selection_tag) as model-level tags.
    """

    java = model.java
    comp_tag = str(java.component().tags()[0])
    geom_tag = str(java.component(comp_tag).geom().tags()[0])
    geom = java.component(comp_tag).geom(geom_tag)

    L = total_length_um(geom_params)
    r_max = geom_params.external_radius_um * 1.1
    eps = 0.5  # µm tolerance for "on the face"

    # Remove any previous endcap selections (idempotency)
    for t in ("sel_inlet", "sel_outlet"):
        existing = [str(x) for x in geom.feature().tags()]
        if t in existing:
            geom.feature().remove(t)

    _add_box_selection(
        geom, "sel_inlet", "Inlet face (z=0)",
        entity_dim=2,
        xmin=-r_max, xmax=r_max,
        ymin=-r_max, ymax=r_max,
        zmin=-eps,  zmax=eps,
    )
    _add_box_selection(
        geom, "sel_outlet", "Outlet face (z=L)",
        entity_dim=2,
        xmin=-r_max, xmax=r_max,
        ymin=-r_max, ymax=r_max,
        zmin=L - eps, zmax=L + eps,
    )
    geom.run()
    return f"{geom_tag}_sel_inlet", f"{geom_tag}_sel_outlet"


def setup_physics(model: Any, geom_params: GeometryParams) -> None:
    """Add EWFD with scattered-field formulation + matched-BC end-caps."""

    java = model.java
    comp_tag = str(java.component().tags()[0])
    comp = java.component(comp_tag)
    geom_tag = str(comp.geom().tags()[0])

    # Drop any existing EWFD on idempotent re-runs.
    for t in [str(x) for x in comp.physics().tags()]:
        comp.physics().remove(t)

    phys = comp.physics().create("ewfd", "ElectromagneticWavesFrequencyDomain", geom_tag)
    phys.label("Electromagnetic Waves, Frequency Domain")

    # Scattered-field formulation: controlled by the physics interface's
    # BackgroundField property group (NOT the wee1 sub-feature).
    phys.prop("BackgroundField").set("SolveFor", "scatteredField")
    phys.prop("BackgroundField").set("Eb", ["exp(-i*ewfd.k0*z)", "0", "0"])

    # Matched/scattering BC on inlet & outlet end-caps.
    inlet_tag, outlet_tag = add_endcap_selections(model, geom_params)
    for i, sel_tag in enumerate((inlet_tag, outlet_tag), start=1):
        sbc = phys.feature().create(f"sbc{i}", "Scattering", 2)  # 2 = boundary
        sbc.selection().named(sel_tag)
        sbc.label(f"Matched BC ({['inlet', 'outlet'][i - 1]})")


# --- Study & solver --------------------------------------------------------


def setup_study(model: Any, frequency_hz: float) -> None:
    """Add a single-frequency frequency-domain study with MUMPS direct solver."""

    java = model.java
    for t in [str(x) for x in java.study().tags()]:
        java.study().remove(t)

    study = java.study().create("std1")
    study.label("Frequency-Domain Solve")
    step = study.feature().create("freq", "Frequency")
    step.set("plist", str(frequency_hz))
    # Solver auto-generated by study; MUMPS is the default direct solver in 3D EWFD.


def solve_study(model: Any) -> None:
    java = model.java
    study_tag = str(java.study().tags()[0])
    java.study(study_tag).run()


# --- Result extraction -----------------------------------------------------


def _evaluate_at_points(model: Any, expr: str, points_um: np.ndarray) -> np.ndarray:
    """Evaluate `expr` at the given (N, 3) points in µm. Returns (N,) array.

    Uses Cut Point 3D + a numerical evaluation export.
    """

    java = model.java
    # Cut Point 3D dataset
    datasets = java.result().dataset()
    for t in ("cpt_eval",):
        if t in [str(x) for x in datasets.tags()]:
            datasets.remove(t)
    cpt = datasets.create("cpt_eval", "CutPoint3D")
    cpt.set("pointx", [str(p) for p in points_um[:, 0]])
    cpt.set("pointy", [str(p) for p in points_um[:, 1]])
    cpt.set("pointz", [str(p) for p in points_um[:, 2]])

    # Numerical evaluation
    numerical = java.result().numerical()
    for t in ("ev_eval",):
        if t in [str(x) for x in numerical.tags()]:
            numerical.remove(t)
    ev = numerical.create("ev_eval", "EvalPoint")
    ev.set("data", "cpt_eval")
    ev.set("expr", [expr])
    table_values = ev.computeResult()  # returns Java double[][]
    # Last column is the value; first columns are coords
    arr = np.array([[float(v) for v in row] for row in table_values])
    return arr[:, -1]


def extract_axial_profile(
    model: Any,
    geom_params: GeometryParams,
    *,
    n_points: int = 200,
    expr: str = "ewfd.normE",
) -> tuple[np.ndarray, np.ndarray]:
    """|E|(z) on the axis (x=0, y=0). Returns (z_um, value)."""

    L = total_length_um(geom_params)
    z = np.linspace(0.5, L - 0.5, n_points)  # avoid the exact boundaries
    points = np.column_stack([np.zeros_like(z), np.zeros_like(z), z])
    vals = _evaluate_at_points(model, expr, points)
    return z, vals


def extract_axial_slice(
    model: Any,
    geom_params: GeometryParams,
    *,
    nx: int = 60,
    nz: int = 120,
    expr: str = "ewfd.normE",
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """|E|(x, z) at y=0. Returns (x_um, z_um, value[nx, nz])."""

    L = total_length_um(geom_params)
    x = np.linspace(-geom_params.external_radius_um + 0.5,
                     geom_params.external_radius_um - 0.5, nx)
    z = np.linspace(0.5, L - 0.5, nz)
    X, Z = np.meshgrid(x, z, indexing="ij")
    points = np.column_stack([X.ravel(), np.zeros(X.size), Z.ravel()])
    vals = _evaluate_at_points(model, expr, points).reshape(nx, nz)
    return x, z, vals
